/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32l432xx.h>


void delay() {
    for(volatile int i=0; i<100000; ++i)
        ; // do nothing, waste some CPU cycles
}


void init_LED() {
    // enable clock for peripheral component GPIOB
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;     // *(uint32_t *)0x4002104c |= 1 << 1;
    (void)RCC->AHB2ENR; // read-back clock 

    // set pin to output mode (1). Reset defaults for other registers are okay here
    GPIOB->MODER = (GPIOB->MODER & ~GPIO_MODER_MODE3_Msk) | (1 << GPIO_MODER_MODE3_Pos);    // 0x48000400  Msk: 3<<6 1<<6
}

// ODR 0x48000414

int main(void) {

    init_LED();

    /* Loop forever */
	for(;;) {
        GPIOB->BSRR = 1 << 3;
        delay();
        GPIOB->BRR = 1 << 3;
        delay();
    }
}
